version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: dream-vacations-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}  
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p${DB_ROOT_PASSWORD} -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - dreamnet

  backend:
    env_file:
      - ./backend/.env
    build: ./backend
    container_name: dream-vacations-backend
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - dreamnet

  frontend:
    build: ./frontend
    container_name: dream_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    networks:
      - dreamnet



networks:
  dreamnet:

volumes:
  db_data:


